# Uncomment the next line to define a global platform for your project
 platform :ios, '13.2'

target 'PulseEcoSwiftUI' do
  # Comment the next line if you don't want to use dynamic frameworks
  #use_frameworks!

  # Pods for PulseEcoSwiftUI
	pod 'Charts'
	pod 'lottie-ios', ' 2.5.3'
end
